# Header
menu:
  首页: /
  文档: /archives
  标签: /tags
  分类: /categories
  # Github:
  #   url: https://github.com/ZLMisMeNO1
  #   icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: 生活是最好的老师

# URL of the Home page image
index_cover: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg

# Default post title
default_post_title: 未定义

# Comments. Choose one by filling up the information
comments: false
  # Disqus comments
  # disqus_shortname: klugjotest
  # Facebook comments
  # facebook:
  #   appid: 123456789012345
  #   comment_count: 5
  #   comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/ZLMisMeNO1
gitlab_url:
linkedin_url:
mailto: